apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-deployment
  labels:
    app: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service-image
        image: helospark/review-service:0.0.5
        env:
          - name: SPRING_ZIPKIN_BASE-URL
            value: http://zipkin-service.default.svc.cluster.local:9411
        resources:
          limits:
            cpu: 1.0
            memory: 1G
          requests:
            cpu: 0.1
            memory: 1G
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: review-service-service
  labels:
    app: review-service-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: review-service
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: review-service-autoscaler
  labels:
    app: review-service
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: review-deployment
  metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         averageUtilization: 20
         type: Utilization
       