apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-edge-deployment
  labels:
    app: review-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-edge
  template:
    metadata:
      labels:
        app: review-edge
    spec:
      containers:
      - name: review-edge-image
        image: helospark/review-edge:0.0.7
        env:
          - name: review-service-url
            value: http://review-service-service.default.svc.cluster.local:8080
          - name: SPRING_ZIPKIN_BASE-URL
            value: http://zipkin-service.default.svc.cluster.local:9411
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: review-edge-service
  labels:
    app: review-edge
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8081
    protocol: TCP
  selector:
    app: review-edge
