server:
  port: 8080
management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /actuator
      exposure:
        include:
        - '*'
spring:
  zipkin:
    base-url: http://localhost:9411
    compression:
      enabled: true
  application:
    name: review-service
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
project:
  version: 0.0.3